import type { OpenAPIDocument, SpecSummary, OperationInfo } from '../../shared/openapi.js';
import { extractOperations } from '../../shared/openapi.js';
import { operationToMethodName, toPascalCase, toCamelCase } from '../../shared/naming.js';
import { generateTypes, generateTypeString } from './types.js';

export function generateTypescriptClient(
  doc: OpenAPIDocument,
  summary: SpecSummary,
  filterTags?: string[]
): string {
  let operations = extractOperations(doc);

  if (filterTags && filterTags.length > 0) {
    const tagSet = new Set(filterTags);
    operations = operations.filter((op) => op.tags.some((t) => tagSet.has(t)));
  }

  const baseUrl = summary.info.baseUrl ?? 'https://api.example.com';
  const lines: string[] = [];

  // Header
  lines.push(`// Generated by apix — ${summary.info.title} v${summary.info.version}`);
  lines.push(`// ${summary.endpointCount} endpoints, ${summary.schemaCount} schemas`);
  lines.push(`//`);
  lines.push(`// Usage:`);
  lines.push(`//   const client = new ApiClient({ baseUrl: '${baseUrl}' });`);
  lines.push(`//   const result = await client.<method>(params);`);
  lines.push('');

  // Types
  const typesCode = generateTypes(doc);
  if (typesCode.trim()) {
    lines.push('// ── Types ──────────────────────────────────────────');
    lines.push('');
    lines.push(typesCode);
  }

  // Error class
  lines.push('// ── API Error ──────────────────────────────────────');
  lines.push('');
  lines.push(`export class ApiError extends Error {`);
  lines.push(`  constructor(`);
  lines.push(`    message: string,`);
  lines.push(`    public readonly status: number,`);
  lines.push(`    public readonly body: unknown`);
  lines.push(`  ) {`);
  lines.push(`    super(message);`);
  lines.push(`    this.name = 'ApiError';`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');

  // Client options
  lines.push('// ── Client ─────────────────────────────────────────');
  lines.push('');
  lines.push(`export interface ApiClientOptions {`);
  lines.push(`  baseUrl?: string;`);
  lines.push(`  apiKey?: string;`);
  lines.push(`  bearerToken?: string;`);
  lines.push(`  headers?: Record<string, string>;`);
  lines.push(`}`);
  lines.push('');

  // Client class
  lines.push(`export class ApiClient {`);
  lines.push(`  private readonly baseUrl: string;`);
  lines.push(`  private readonly headers: Record<string, string>;`);
  lines.push('');
  lines.push(`  constructor(options: ApiClientOptions = {}) {`);
  lines.push(`    this.baseUrl = (options.baseUrl ?? '${baseUrl}').replace(/\\/+$/, '');`);
  lines.push(`    this.headers = {`);
  lines.push(`      'Content-Type': 'application/json',`);
  lines.push(`      ...options.headers,`);
  lines.push(`    };`);
  lines.push(`    if (options.bearerToken) {`);
  lines.push(`      this.headers['Authorization'] = \`Bearer \${options.bearerToken}\`;`);
  lines.push(`    } else if (options.apiKey) {`);
  lines.push(`      this.headers['Authorization'] = \`Bearer \${options.apiKey}\`;`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push('');

  // Fetch helper with retry
  lines.push(`  private async request<T>(`);
  lines.push(`    method: string,`);
  lines.push(`    path: string,`);
  lines.push(`    options: { query?: Record<string, string>; body?: unknown } = {}`);
  lines.push(`  ): Promise<T> {`);
  lines.push(`    let url = \`\${this.baseUrl}\${path}\`;`);
  lines.push(`    if (options.query) {`);
  lines.push(`      const params = new URLSearchParams();`);
  lines.push(`      for (const [k, v] of Object.entries(options.query)) {`);
  lines.push(`        if (v !== undefined && v !== null) params.set(k, String(v));`);
  lines.push(`      }`);
  lines.push(`      const qs = params.toString();`);
  lines.push(`      if (qs) url += \`?\${qs}\`;`);
  lines.push(`    }`);
  lines.push('');
  lines.push(`    const init: RequestInit = {`);
  lines.push(`      method,`);
  lines.push(`      headers: { ...this.headers },`);
  lines.push(`    };`);
  lines.push(`    if (options.body !== undefined) {`);
  lines.push(`      init.body = JSON.stringify(options.body);`);
  lines.push(`    }`);
  lines.push('');
  lines.push(`    let lastError: Error | null = null;`);
  lines.push(`    for (let attempt = 0; attempt < 3; attempt++) {`);
  lines.push(`      if (attempt > 0) {`);
  lines.push(`        await new Promise((r) => setTimeout(r, Math.pow(2, attempt) * 500));`);
  lines.push(`      }`);
  lines.push(`      const res = await fetch(url, init);`);
  lines.push(`      if (res.status === 429 || res.status >= 500) {`);
  lines.push(`        lastError = new ApiError(\`HTTP \${res.status}\`, res.status, null);`);
  lines.push(`        continue;`);
  lines.push(`      }`);
  lines.push(`      if (!res.ok) {`);
  lines.push(`        const body = await res.text().catch(() => '');`);
  lines.push(`        throw new ApiError(\`HTTP \${res.status}: \${body}\`, res.status, body);`);
  lines.push(`      }`);
  lines.push(`      if (res.status === 204) return undefined as T;`);
  lines.push(`      return (await res.json()) as T;`);
  lines.push(`    }`);
  lines.push(`    throw lastError ?? new Error('Request failed');`);
  lines.push(`  }`);
  lines.push('');

  // Methods
  for (const op of operations) {
    const methodName = operationToMethodName(op.method, op.path, op.operationId);
    const { paramsType, paramsArg, pathExpr, queryMapping, bodyMapping } = buildMethodParams(op);

    const description = op.summary || op.description || `${op.method.toUpperCase()} ${op.path}`;
    lines.push(`  /** ${description} */`);

    const returnType = getReturnType(op);
    lines.push(`  async ${methodName}(${paramsArg}): Promise<${returnType}> {`);

    const pathStr = pathExpr;
    if (queryMapping || bodyMapping) {
      const opts: string[] = [];
      if (queryMapping) opts.push(`query: ${queryMapping}`);
      if (bodyMapping) opts.push(`body: ${bodyMapping}`);
      lines.push(`    return this.request<${returnType}>('${op.method.toUpperCase()}', ${pathStr}, { ${opts.join(', ')} });`);
    } else {
      lines.push(`    return this.request<${returnType}>('${op.method.toUpperCase()}', ${pathStr});`);
    }

    lines.push(`  }`);
    lines.push('');
  }

  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

interface MethodParamResult {
  paramsType: string;
  paramsArg: string;
  pathExpr: string;
  queryMapping?: string;
  bodyMapping?: string;
}

function buildMethodParams(op: OperationInfo): MethodParamResult {
  const pathParams = op.parameters.filter((p) => p.in === 'path');
  const queryParams = op.parameters.filter((p) => p.in === 'query');
  const hasBody = !!op.requestBody;

  const fields: string[] = [];

  for (const p of pathParams) {
    fields.push(`${toCamelCase(p.name)}: string`);
  }
  for (const p of queryParams) {
    const opt = p.required ? '' : '?';
    const type = schemaToInlineType(p.schema);
    fields.push(`${toCamelCase(p.name)}${opt}: ${type}`);
  }
  if (hasBody) {
    const bodyType = op.requestBody
      ? schemaToInlineType(op.requestBody.schema)
      : 'unknown';
    const opt = op.requestBody?.required ? '' : '?';
    fields.push(`body${opt}: ${bodyType}`);
  }

  if (fields.length === 0) {
    // Build path expression
    let pathExpr = `\`${op.path}\``;
    if (!op.path.includes('{')) {
      pathExpr = `'${op.path}'`;
    }
    return { paramsType: '', paramsArg: '', pathExpr };
  }

  const paramsType = `{ ${fields.join('; ')} }`;
  const paramsArg = `params: ${paramsType}`;

  // Build path expression
  let pathExpr: string;
  if (op.path.includes('{')) {
    const replaced = op.path.replace(/\{([^}]+)\}/g, (_, name: string) => {
      return `\${params.${toCamelCase(name)}}`;
    });
    pathExpr = `\`${replaced}\``;
  } else {
    pathExpr = `'${op.path}'`;
  }

  // Query mapping
  let queryMapping: string | undefined;
  if (queryParams.length > 0) {
    const entries = queryParams.map((p) => {
      const key = p.name;
      const value = `params.${toCamelCase(p.name)}`;
      if (key === toCamelCase(p.name)) {
        return `${key}: String(${value} ?? '')`;
      }
      return `'${key}': String(${value} ?? '')`;
    });
    queryMapping = `{ ${entries.join(', ')} } as Record<string, string>`;
  }

  // Body mapping
  let bodyMapping: string | undefined;
  if (hasBody) {
    bodyMapping = 'params.body';
  }

  return { paramsType, paramsArg, pathExpr, queryMapping, bodyMapping };
}

function schemaToInlineType(schema: Record<string, unknown>): string {
  if (!schema) return 'unknown';
  const type = schema['type'] as string | undefined;
  if (type === 'string') return 'string';
  if (type === 'number' || type === 'integer') return 'number';
  if (type === 'boolean') return 'boolean';
  if (type === 'array') {
    const items = schema['items'] as Record<string, unknown> | undefined;
    const itemType = items ? schemaToInlineType(items) : 'unknown';
    return `Array<${itemType}>`;
  }
  if (type === 'object' || schema['properties']) return 'Record<string, unknown>';
  return 'unknown';
}

function getReturnType(op: OperationInfo): string {
  const successResponse = op.responses.find(
    (r) => r.statusCode.startsWith('2') && r.schema
  );
  if (!successResponse?.schema) return 'unknown';
  return schemaToInlineType(successResponse.schema);
}
