import type { OpenAPIDocument, SpecSummary, OperationInfo } from '../shared/openapi.js';
import { extractOperations } from '../shared/openapi.js';
import { operationToToolName } from '../shared/naming.js';
import type { AuthConfig } from '../shared/auth-detector.js';

export interface McpToolDef {
  name: string;
  description: string;
  method: string;
  path: string;
  inputSchema: Record<string, unknown>;
}

export function generateMcpTools(
  doc: OpenAPIDocument,
  filterTags?: string[]
): McpToolDef[] {
  let operations = extractOperations(doc);

  if (filterTags && filterTags.length > 0) {
    const tagSet = new Set(filterTags);
    operations = operations.filter((op) => op.tags.some((t) => tagSet.has(t)));
  }

  return operations.map((op) => operationToMcpTool(op));
}

function operationToMcpTool(op: OperationInfo): McpToolDef {
  const name = operationToToolName(op.method, op.path, op.operationId);
  const description = op.summary || op.description || `${op.method.toUpperCase()} ${op.path}`;

  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const param of op.parameters) {
    properties[param.name] = {
      ...param.schema,
      description: param.description,
    };
    if (param.required) {
      required.push(param.name);
    }
  }

  if (op.requestBody) {
    const bodySchema = op.requestBody.schema;
    if (bodySchema && typeof bodySchema === 'object' && bodySchema['properties']) {
      const bodyProps = bodySchema['properties'] as Record<string, unknown>;
      const bodyRequired = (bodySchema['required'] ?? []) as string[];
      for (const [key, val] of Object.entries(bodyProps)) {
        properties[key] = val;
      }
      if (op.requestBody.required) {
        required.push(...bodyRequired);
      }
    } else if (bodySchema) {
      properties['body'] = {
        ...bodySchema,
        description: op.requestBody.description ?? 'Request body',
      };
      if (op.requestBody.required) {
        required.push('body');
      }
    }
  }

  return {
    name,
    description,
    method: op.method.toUpperCase(),
    path: op.path,
    inputSchema: {
      type: 'object',
      properties,
      ...(required.length > 0 ? { required } : {}),
    },
  };
}

export function generateMcpServer(
  doc: OpenAPIDocument,
  summary: SpecSummary,
  auth: AuthConfig,
  filterTags?: string[]
): string {
  const tools = generateMcpTools(doc, filterTags);
  const baseUrl = summary.info.baseUrl ?? 'https://api.example.com';

  const lines: string[] = [];
  lines.push(`// Generated by apix — MCP Server for ${summary.info.title} v${summary.info.version}`);
  lines.push(`// ${tools.length} tools available`);
  lines.push(`//`);
  lines.push(`// Run: npx tsx mcp-server.ts`);
  lines.push(`// Or add to Claude Desktop config (see README)`);
  lines.push('');
  lines.push(`import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';`);
  lines.push(`import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';`);
  lines.push(`import { z } from 'zod';`);
  lines.push('');
  lines.push(`const BASE_URL = process.env['APIX_BASE_URL'] ?? '${baseUrl}';`);
  lines.push(`const API_KEY = process.env['${auth.envVar || 'APIX_API_KEY'}'] ?? '';`);
  lines.push('');

  // Auth header helper
  lines.push(`function authHeaders(): Record<string, string> {`);
  lines.push(`  const headers: Record<string, string> = { 'Content-Type': 'application/json' };`);
  lines.push(`  if (!API_KEY) return headers;`);

  if (auth.type === 'apiKey' && auth.headerName) {
    lines.push(`  headers['${auth.headerName}'] = API_KEY;`);
  } else if (auth.type === 'basic') {
    lines.push(`  headers['Authorization'] = \`Basic \${API_KEY}\`;`);
  } else {
    lines.push(`  headers['Authorization'] = \`Bearer \${API_KEY}\`;`);
  }

  lines.push(`  return headers;`);
  lines.push(`}`);
  lines.push('');

  // Request helper
  lines.push(`async function apiRequest(method: string, path: string, params: Record<string, unknown> = {}): Promise<unknown> {`);
  lines.push(`  let url = \`\${BASE_URL}\${path}\`;`);
  lines.push(`  const pathParams = path.match(/\\{([^}]+)\\}/g) ?? [];`);
  lines.push(`  for (const pp of pathParams) {`);
  lines.push(`    const key = pp.slice(1, -1);`);
  lines.push(`    if (params[key] !== undefined) {`);
  lines.push(`      url = url.replace(pp, String(params[key]));`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push('');
  lines.push(`  const init: RequestInit = { method, headers: authHeaders() };`);
  lines.push(`  if (['POST', 'PUT', 'PATCH'].includes(method)) {`);
  lines.push(`    const bodyParams: Record<string, unknown> = {};`);
  lines.push(`    const pathKeys = new Set(pathParams.map((pp) => pp.slice(1, -1)));`);
  lines.push(`    for (const [k, v] of Object.entries(params)) {`);
  lines.push(`      if (!pathKeys.has(k)) bodyParams[k] = v;`);
  lines.push(`    }`);
  lines.push(`    if (Object.keys(bodyParams).length > 0) {`);
  lines.push(`      init.body = JSON.stringify(bodyParams);`);
  lines.push(`    }`);
  lines.push(`  } else {`);
  lines.push(`    const query = new URLSearchParams();`);
  lines.push(`    const pathKeys = new Set(pathParams.map((pp) => pp.slice(1, -1)));`);
  lines.push(`    for (const [k, v] of Object.entries(params)) {`);
  lines.push(`      if (!pathKeys.has(k) && v !== undefined) query.set(k, String(v));`);
  lines.push(`    }`);
  lines.push(`    const qs = query.toString();`);
  lines.push(`    if (qs) url += \`?\${qs}\`;`);
  lines.push(`  }`);
  lines.push('');
  lines.push(`  const res = await fetch(url, init);`);
  lines.push(`  if (!res.ok) {`);
  lines.push(`    const text = await res.text().catch(() => '');`);
  lines.push(`    throw new Error(\`HTTP \${res.status}: \${text}\`);`);
  lines.push(`  }`);
  lines.push(`  if (res.status === 204) return { success: true };`);
  lines.push(`  return res.json();`);
  lines.push(`}`);
  lines.push('');

  // Server setup
  lines.push(`const server = new McpServer({`);
  lines.push(`  name: '${summary.info.title}',`);
  lines.push(`  version: '${summary.info.version}',`);
  lines.push(`});`);
  lines.push('');

  // Register tools
  for (const tool of tools) {
    const schemaProps = (tool.inputSchema.properties ?? {}) as Record<string, Record<string, unknown>>;
    const requiredArr = (tool.inputSchema.required ?? []) as string[];
    const requiredSet = new Set(requiredArr);

    // Build zod schema entries
    const zodEntries: string[] = [];
    for (const [propName, propSchema] of Object.entries(schemaProps)) {
      const zodType = jsonSchemaToZod(propSchema, requiredSet.has(propName));
      const desc = (propSchema['description'] as string) ?? '';
      if (desc) {
        zodEntries.push(`    ${propName}: ${zodType}.describe(${JSON.stringify(desc)})`);
      } else {
        zodEntries.push(`    ${propName}: ${zodType}`);
      }
    }

    const escapedDesc = tool.description.replace(/'/g, "\\'");
    lines.push(`server.tool(`);
    lines.push(`  '${tool.name}',`);
    lines.push(`  '${escapedDesc}',`);
    if (zodEntries.length > 0) {
      lines.push(`  {`);
      lines.push(zodEntries.join(',\n'));
      lines.push(`  },`);
    } else {
      lines.push(`  {},`);
    }
    lines.push(`  async (params) => {`);
    lines.push(`    try {`);
    lines.push(`      const result = await apiRequest('${tool.method}', '${tool.path}', params as Record<string, unknown>);`);
    lines.push(`      return { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }] };`);
    lines.push(`    } catch (err) {`);
    lines.push(`      const msg = err instanceof Error ? err.message : String(err);`);
    lines.push(`      return { content: [{ type: 'text', text: \`Error: \${msg}\` }], isError: true };`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`);`);
    lines.push('');
  }

  // Start server
  lines.push(`const transport = new StdioServerTransport();`);
  lines.push(`server.connect(transport).then(() => {`);
  lines.push(`  console.error('MCP server running on stdio');`);
  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
}

function jsonSchemaToZod(schema: Record<string, unknown>, required: boolean): string {
  let base: string;
  const type = schema['type'] as string | undefined;

  switch (type) {
    case 'string':
      base = 'z.string()';
      break;
    case 'number':
    case 'integer':
      base = 'z.number()';
      break;
    case 'boolean':
      base = 'z.boolean()';
      break;
    case 'array':
      base = 'z.array(z.unknown())';
      break;
    case 'object':
      base = 'z.object({}).passthrough()';
      break;
    default:
      base = 'z.unknown()';
  }

  if (!required) {
    base += '.optional()';
  }

  return base;
}
