import type { OpenAPIDocument, OperationInfo, SpecSummary } from '../../shared/openapi.js';
import { extractOperations } from '../../shared/openapi.js';
import { operationToMethodName, toPascalCase, toSnakeCase } from '../../shared/naming.js';

interface SchemaObject {
  type?: string;
  format?: string;
  description?: string;
  properties?: Record<string, SchemaObject>;
  required?: string[];
  items?: SchemaObject;
  enum?: unknown[];
  allOf?: SchemaObject[];
  oneOf?: SchemaObject[];
  anyOf?: SchemaObject[];
  nullable?: boolean;
  $ref?: string;
  additionalProperties?: boolean | SchemaObject;
}

interface FieldDefinition {
  identifier: string;
  type: string;
  required: boolean;
  description?: string;
}

interface TypedDictShape {
  bases: string[];
  requiredFields: FieldDefinition[];
  optionalFields: FieldDefinition[];
}

interface MethodParam {
  identifier: string;
  type: string;
  required: boolean;
}

interface MethodShape {
  methodName: string;
  signature: string[];
  pathExpr: string;
  queryExpr?: string;
  bodyArg?: string;
  returnType: string;
  description: string;
}

const PYTHON_KEYWORDS = new Set([
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield',
]);

export function generatePythonClient(
  doc: OpenAPIDocument,
  summary: SpecSummary,
  filterTags?: string[]
): string {
  let operations = extractOperations(doc);

  if (filterTags && filterTags.length > 0) {
    const tagSet = new Set(filterTags);
    operations = operations.filter((op) => op.tags.some((tag) => tagSet.has(tag)));
  }

  const baseUrl = summary.info.baseUrl ?? 'https://api.example.com';
  const lines: string[] = [];

  lines.push(`# Generated by apix - ${summary.info.title} v${summary.info.version}`);
  lines.push(`# ${summary.endpointCount} endpoints, ${summary.schemaCount} schemas`);
  lines.push('#');
  lines.push('# Usage:');
  lines.push(`#   client = Client(base_url=${pythonLiteral(baseUrl)})`);
  lines.push('#   result = client.some_operation()');
  lines.push('');
  lines.push('from __future__ import annotations');
  lines.push('');
  lines.push('import time');
  lines.push('from typing import Any, Literal, Optional, TypeAlias, TypedDict, cast');
  lines.push('');
  lines.push('import requests');
  lines.push('');

  const typesCode = generatePythonTypes(doc);
  if (typesCode.trim()) {
    lines.push('# Types');
    lines.push('');
    lines.push(typesCode);
    lines.push('');
  }

  lines.push('class ApiError(Exception):');
  lines.push('    def __init__(self, message: str, status: int, body: Any) -> None:');
  lines.push('        super().__init__(message)');
  lines.push('        self.status = status');
  lines.push('        self.body = body');
  lines.push('');
  lines.push('');

  lines.push('class Client:');
  lines.push(
    `    def __init__(self, base_url: str = ${pythonLiteral(baseUrl)}, api_key: Optional[str] = None) -> None:`
  );
  lines.push("        self.base_url = base_url.rstrip('/')");
  lines.push("        self.headers: dict[str, str] = {'Content-Type': 'application/json'}");
  lines.push('        if api_key:');
  lines.push("            self.headers['Authorization'] = f'Bearer {api_key}'");
  lines.push('');
  lines.push(
    '    def _request(self, method: str, path: str, *, params: Optional[dict[str, Any]] = None, json_body: Any = None) -> Any:'
  );
  lines.push('        url = f"{self.base_url}{path}"');
  lines.push('        cleaned_params = {key: value for key, value in (params or {}).items() if value is not None}');
  lines.push('        last_error: Optional[ApiError] = None');
  lines.push('');
  lines.push('        for attempt in range(3):');
  lines.push('            if attempt > 0:');
  lines.push('                time.sleep(0.5 * (2 ** attempt))');
  lines.push('');
  lines.push(
    '            response = requests.request(method, url, headers=dict(self.headers), params=cleaned_params or None, json=json_body, timeout=30)'
  );
  lines.push('');
  lines.push('            if response.status_code == 429 or response.status_code >= 500:');
  lines.push('                body = self._decode_body(response)');
  lines.push('                last_error = ApiError(f"HTTP {response.status_code}", response.status_code, body)');
  lines.push('                continue');
  lines.push('');
  lines.push('            if not response.ok:');
  lines.push('                body = self._decode_body(response)');
  lines.push('                raise ApiError(f"HTTP {response.status_code}: {body}", response.status_code, body)');
  lines.push('');
  lines.push('            if response.status_code == 204:');
  lines.push('                return None');
  lines.push('');
  lines.push('            if not response.content:');
  lines.push('                return None');
  lines.push('');
  lines.push('            return self._decode_body(response)');
  lines.push('');
  lines.push("        raise last_error or ApiError('Request failed', 0, None)");
  lines.push('');
  lines.push('    @staticmethod');
  lines.push('    def _decode_body(response: requests.Response) -> Any:');
  lines.push('        try:');
  lines.push('            return response.json()');
  lines.push('        except ValueError:');
  lines.push('            return response.text');
  lines.push('');

  for (const op of operations) {
    const method = buildMethod(op);
    lines.push(`    def ${method.methodName}(${method.signature.join(', ')}) -> ${method.returnType}:`);
    lines.push(`        """${escapeDocstring(method.description)}"""`);

    if (method.queryExpr) {
      lines.push(`        params = ${method.queryExpr}`);
    }

    const requestArgs = [`${pythonLiteral(op.method.toUpperCase())}`, method.pathExpr];
    if (method.queryExpr) {
      requestArgs.push('params=params');
    }
    if (method.bodyArg) {
      requestArgs.push(`json_body=${method.bodyArg}`);
    }
    const requestCall = `self._request(${requestArgs.join(', ')})`;

    if (method.returnType === 'None') {
      lines.push(`        ${requestCall}`);
      lines.push('        return None');
    } else if (method.returnType === 'Any') {
      lines.push(`        return ${requestCall}`);
    } else {
      lines.push(`        return cast(${method.returnType}, ${requestCall})`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

export function generatePythonTypes(doc: OpenAPIDocument): string {
  const schemas = (doc.components?.schemas ?? {}) as Record<string, SchemaObject>;
  const lines: string[] = [];

  for (const [rawName, schema] of Object.entries(schemas)) {
    const name = sanitizePascalIdentifier(rawName);

    if (schema.description) {
      lines.push(`"""${escapeDocstring(schema.description)}"""`);
    }

    const rendered = renderSchemaDeclaration(name, schema);
    lines.push(...rendered);
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

function renderSchemaDeclaration(name: string, schema: SchemaObject): string[] {
  const shape = getTypedDictShape(schema);
  if (shape) {
    return renderTypedDictClasses(name, shape);
  }

  const typeExpr = schemaToPythonType(schema);
  return [`${name}: TypeAlias = ${typeExpr}`];
}

function renderTypedDictClasses(name: string, shape: TypedDictShape): string[] {
  const lines: string[] = [];
  const baseList = shape.bases.length > 0 ? shape.bases.join(', ') : 'TypedDict';

  if (shape.requiredFields.length > 0 && shape.optionalFields.length > 0) {
    const requiredName = `${name}Required`;
    lines.push(`class ${requiredName}(${baseList}):`);
    lines.push(...renderTypedDictFields(shape.requiredFields, 1));
    lines.push('');
    lines.push(`class ${name}(${requiredName}, total=False):`);
    lines.push(...renderTypedDictFields(shape.optionalFields, 1));
    return lines;
  }

  const classDecl =
    shape.optionalFields.length > 0 && shape.requiredFields.length === 0
      ? `class ${name}(${baseList}, total=False):`
      : `class ${name}(${baseList}):`;

  lines.push(classDecl);
  lines.push(
    ...renderTypedDictFields(
      shape.requiredFields.length > 0 ? shape.requiredFields : shape.optionalFields,
      1
    )
  );
  return lines;
}

function renderTypedDictFields(fields: FieldDefinition[], indent: number): string[] {
  if (fields.length === 0) {
    return [`${pad(indent)}pass`];
  }

  const lines: string[] = [];
  for (const field of fields) {
    if (field.description) {
      lines.push(`${pad(indent)}# ${field.description}`);
    }
    lines.push(`${pad(indent)}${field.identifier}: ${field.type}`);
  }
  return lines;
}

function getTypedDictShape(schema: SchemaObject): TypedDictShape | null {
  if (schema.oneOf || schema.anyOf) {
    return null;
  }

  const bases: string[] = [];
  const inlineProperties: Record<string, SchemaObject> = {};
  const inlineRequired = new Set<string>();
  let sawObjectShape = false;

  const absorb = (candidate: SchemaObject | undefined): void => {
    if (!candidate) return;

    if (candidate.$ref) {
      bases.push(refToTypeName(candidate.$ref));
      return;
    }

    if (candidate.type === 'object' || candidate.properties || candidate.additionalProperties || candidate.allOf) {
      sawObjectShape = true;
    }

    if (candidate.allOf) {
      for (const part of candidate.allOf) {
        absorb(part);
      }
    }

    for (const [propName, propSchema] of Object.entries(candidate.properties ?? {})) {
      inlineProperties[propName] = propSchema;
    }
    for (const requiredName of candidate.required ?? []) {
      inlineRequired.add(requiredName);
    }
  };

  absorb(schema);

  if (!sawObjectShape && bases.length === 0) {
    return null;
  }

  if (schema.additionalProperties && Object.keys(inlineProperties).length === 0) {
    return null;
  }

  const requiredFields: FieldDefinition[] = [];
  const optionalFields: FieldDefinition[] = [];

  for (const [propName, propSchema] of Object.entries(inlineProperties)) {
    const field: FieldDefinition = {
      identifier: sanitizeSnakeIdentifier(propName),
      type: schemaToPythonType(propSchema),
      required: inlineRequired.has(propName),
      description: propSchema.description,
    };

    if (field.required) {
      requiredFields.push(field);
    } else {
      optionalFields.push(field);
    }
  }

  return { bases: dedupeStrings(bases), requiredFields, optionalFields };
}

function buildMethod(op: OperationInfo): MethodShape {
  const methodName = sanitizeSnakeIdentifier(
    toSnakeCase(operationToMethodName(op.method, op.path, op.operationId))
  );
  const signature: string[] = ['self'];
  const requiredArgs: string[] = [];
  const optionalArgs: string[] = [];
  const pathParams = op.parameters.filter((param) => param.in === 'path');
  const queryParams = op.parameters.filter((param) => param.in === 'query');

  const methodParams: MethodParam[] = [];

  for (const param of pathParams) {
    methodParams.push({
      identifier: sanitizeSnakeIdentifier(param.name),
      type: schemaToPythonType(param.schema as SchemaObject),
      required: true,
    });
  }

  for (const param of queryParams) {
    const type = schemaToPythonType(param.schema as SchemaObject);
    methodParams.push({
      identifier: sanitizeSnakeIdentifier(param.name),
      type: param.required ? type : `Optional[${type}]`,
      required: param.required,
    });
  }

  for (const param of methodParams) {
    if (param.required) {
      requiredArgs.push(`${param.identifier}: ${param.type}`);
    } else {
      optionalArgs.push(`${param.identifier}: ${param.type} = None`);
    }
  }

  let bodyArg: string | undefined;
  if (op.requestBody) {
    const bodyType = schemaToPythonType(op.requestBody.schema as SchemaObject);
    if (op.requestBody.required) {
      requiredArgs.push(`body: ${bodyType}`);
    } else {
      optionalArgs.push(`body: Optional[${bodyType}] = None`);
    }
    bodyArg = 'body';
  }

  signature.push(...requiredArgs, ...optionalArgs);

  const description = op.summary || op.description || `${op.method.toUpperCase()} ${op.path}`;
  const pathExpr = buildPathExpression(op.path);
  const queryExpr =
    queryParams.length > 0
      ? `{ ${queryParams
          .map((param) => `${pythonLiteral(param.name)}: ${sanitizeSnakeIdentifier(param.name)}`)
          .join(', ')} }`
      : undefined;

  return {
    methodName,
    signature,
    pathExpr,
    queryExpr,
    bodyArg,
    returnType: getReturnType(op),
    description,
  };
}

function buildPathExpression(path: string): string {
  if (!path.includes('{')) {
    return pythonLiteral(path);
  }

  const replaced = path.replace(/\{([^}]+)\}/g, (_, name: string) => `{${sanitizeSnakeIdentifier(name)}}`);
  return `f${pythonLiteral(replaced)}`;
}

function getReturnType(op: OperationInfo): string {
  if (op.responses.some((response) => response.statusCode === '204')) {
    return 'None';
  }

  const successResponse = op.responses.find((response) => response.statusCode.startsWith('2') && response.schema);
  if (!successResponse?.schema) {
    return 'Any';
  }

  return schemaToPythonType(successResponse.schema as SchemaObject);
}

function schemaToPythonType(schema: SchemaObject | undefined): string {
  if (!schema) return 'Any';

  if (schema.$ref) {
    return refToTypeName(schema.$ref);
  }

  if (schema.nullable) {
    return `Optional[${schemaToPythonType({ ...schema, nullable: false })}]`;
  }

  if (schema.enum) {
    return literalUnion(schema.enum);
  }

  if (schema.oneOf || schema.anyOf) {
    const variants = schema.oneOf ?? schema.anyOf ?? [];
    return dedupeStrings(variants.map((variant) => schemaToPythonType(variant))).join(' | ') || 'Any';
  }

  if (schema.allOf) {
    const nonRefParts = schema.allOf.filter((part) => !part.$ref);
    if (nonRefParts.length > 0 && nonRefParts.every((part) => part.type === 'object' || part.properties)) {
      return 'dict[str, Any]';
    }
    const refParts = schema.allOf
      .filter((part) => part.$ref)
      .map((part) => refToTypeName(part.$ref as string));
    return refParts[0] ?? 'dict[str, Any]';
  }

  if (schema.type === 'array') {
    return `list[${schemaToPythonType(schema.items)}]`;
  }

  if (schema.type === 'object' || schema.properties) {
    if (schema.additionalProperties && !schema.properties) {
      const valueType =
        typeof schema.additionalProperties === 'object'
          ? schemaToPythonType(schema.additionalProperties)
          : 'Any';
      return `dict[str, ${valueType}]`;
    }
    return 'dict[str, Any]';
  }

  switch (schema.type) {
    case 'string':
      return 'str';
    case 'integer':
      return 'int';
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    default:
      return 'Any';
  }
}

function literalUnion(values: unknown[]): string {
  return `Literal[${values.map((value) => pythonLiteral(value)).join(', ')}]`;
}

function refToTypeName(ref: string): string {
  const tail = ref.split('/').at(-1) ?? ref;
  return sanitizePascalIdentifier(tail);
}

function sanitizePascalIdentifier(value: string): string {
  const candidate = toPascalCase(value) || 'GeneratedType';
  return sanitizeIdentifier(candidate);
}

function sanitizeSnakeIdentifier(value: string): string {
  const candidate = toSnakeCase(value) || 'value';
  return sanitizeIdentifier(candidate);
}

function sanitizeIdentifier(value: string): string {
  let result = value.replace(/[^a-zA-Z0-9_]/g, '_');
  if (!result) result = 'value';
  if (/^[0-9]/.test(result)) {
    result = `_${result}`;
  }
  if (PYTHON_KEYWORDS.has(result)) {
    result = `${result}_`;
  }
  return result;
}

function pythonLiteral(value: unknown): string {
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }
  if (typeof value === 'number') {
    return Number.isFinite(value) ? String(value) : 'None';
  }
  if (typeof value === 'boolean') {
    return value ? 'True' : 'False';
  }
  if (value === null || value === undefined) {
    return 'None';
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => pythonLiteral(item)).join(', ')}]`;
  }
  return JSON.stringify(value);
}

function escapeDocstring(text: string): string {
  return text.replace(/"""/g, '\\"\\"\\"');
}

function pad(indent: number): string {
  return '    '.repeat(indent);
}

function dedupeStrings(values: string[]): string[] {
  return [...new Set(values.filter(Boolean))];
}
