import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { logger } from '../utils/logger.js';
import { writeConfig, type ApixConfig } from '../utils/config.js';
import { fetchSpec } from '../../discovery/fetcher.js';
import { resolveSpec } from '../../discovery/resolver.js';
import { generateTypescriptClient } from '../../codegen/typescript/client.js';
import { generatePythonClient } from '../../codegen/python/client.js';
import { generateMcpServer } from '../../mcp/generator.js';
import { generateAuthDocs } from '../../mcp/auth.js';
import { detectAuth } from '../../shared/auth-detector.js';
import { toSlug } from '../../shared/naming.js';
import { ApixError } from '../../shared/errors.js';

export interface InitOptions {
  output?: string;
  tags?: string;
  languages?: string;
}

const VALID_LANGUAGES = new Set(['typescript', 'ts', 'python', 'py']);

function parseLanguages(input: string | undefined): Set<'typescript' | 'python'> {
  if (!input) return new Set(['typescript']);
  const result = new Set<'typescript' | 'python'>();
  for (const raw of input.split(',')) {
    const lang = raw.trim().toLowerCase();
    if (!VALID_LANGUAGES.has(lang)) {
      throw new ApixError(
        `Unknown language: ${raw}`,
        'Supported languages: typescript, python'
      );
    }
    if (lang === 'ts' || lang === 'typescript') result.add('typescript');
    if (lang === 'py' || lang === 'python') result.add('python');
  }
  return result;
}

export async function initCommand(spec: string, options: InitOptions): Promise<void> {
  const startTime = Date.now();

  try {
    logger.spin(`Fetching OpenAPI spec from ${spec}`);
    const doc = await fetchSpec(spec);

    const summary = resolveSpec(doc);
    logger.success(`Found ${summary.endpointCount} endpoints, ${summary.schemaCount} schemas`);

    const slug = toSlug(summary.info.title || 'api');
    const outDir = resolve(options.output ?? `./${slug}`);
    await mkdir(outDir, { recursive: true });

    const auth = detectAuth(doc);

    const filterTags = options.tags?.split(',').map((t) => t.trim());
    const languages = parseLanguages(options.languages);

    const generatedFiles: Array<[string, string]> = [];

    if (languages.has('typescript')) {
      logger.spin('Generating TypeScript client...');
      const clientCode = generateTypescriptClient(doc, summary, filterTags);
      await writeFile(join(outDir, 'client.ts'), clientCode, 'utf-8');
      logger.success(`Generated: ${join(outDir, 'client.ts')} (single file, 0 deps)`);
      generatedFiles.push(['Client (TS)', 'client.ts']);
    }

    if (languages.has('python')) {
      logger.spin('Generating Python client...');
      const pythonCode = generatePythonClient(doc, summary, filterTags);
      await writeFile(join(outDir, 'client.py'), pythonCode, 'utf-8');
      logger.success(`Generated: ${join(outDir, 'client.py')} (requires: requests)`);
      generatedFiles.push(['Client (Python)', 'client.py']);
    }

    logger.spin('Generating MCP server...');
    const mcpCode = generateMcpServer(doc, summary, auth, filterTags);
    await writeFile(join(outDir, 'mcp-server.ts'), mcpCode, 'utf-8');
    logger.success(`Generated: ${join(outDir, 'mcp-server.ts')}`);
    generatedFiles.push(['MCP Server', 'mcp-server.ts']);

    const readmeContent = buildProjectReadme(summary, auth);
    await writeFile(join(outDir, 'README.md'), readmeContent, 'utf-8');
    generatedFiles.push(['README', 'README.md']);

    const config: ApixConfig = {
      baseUrl: summary.info.baseUrl ?? '',
      authType: auth.type,
      authEnvVar: auth.envVar,
      specPath: spec,
      generatedAt: new Date().toISOString(),
    };
    await writeConfig(outDir, config);

    logger.newline();
    logger.success(`Output directory: ${outDir}`);
    logger.newline();
    logger.table([...generatedFiles, ['Config', 'apix.config.json']]);
    logger.newline();

    if (auth.type !== 'none') {
      logger.info(`Auth: ${auth.description}`);
      logger.info(`Set ${auth.envVar} before running the MCP server`);
      logger.newline();
    }

    logger.info(`Run: npx apix serve ${outDir}`);
    logger.done(startTime);
  } catch (err) {
    if (err instanceof ApixError) {
      logger.error(err.message, err.suggestion);
    } else {
      logger.error(String(err));
    }
    process.exitCode = 1;
  }
}

function buildProjectReadme(
  summary: ReturnType<typeof resolveSpec>,
  auth: ReturnType<typeof detectAuth>
): string {
  const lines: string[] = [];
  lines.push(`# ${summary.info.title}`);
  lines.push('');
  lines.push(`Generated by [apix](https://github.com/apix/apix) from an OpenAPI spec.`);
  lines.push('');
  lines.push(`- **Version:** ${summary.info.version}`);
  lines.push(`- **Endpoints:** ${summary.endpointCount}`);
  lines.push(`- **Schemas:** ${summary.schemaCount}`);
  if (summary.info.baseUrl) {
    lines.push(`- **Base URL:** ${summary.info.baseUrl}`);
  }
  lines.push('');
  lines.push('## Files');
  lines.push('');
  lines.push('| File | Purpose |');
  lines.push('| --- | --- |');
  lines.push('| `client.ts` | Typed TypeScript client (optional) |');
  lines.push('| `client.py` | Python `requests` client (optional) |');
  lines.push('| `mcp-server.ts` | MCP server exposing each endpoint as a tool |');
  lines.push('| `apix.config.json` | apix project metadata |');
  lines.push('');
  lines.push('## Run the MCP server');
  lines.push('');
  lines.push('```bash');
  lines.push('npx apix serve .');
  lines.push('```');
  lines.push('');
  lines.push('Or plug it directly into a Claude Desktop `mcpServers` entry:');
  lines.push('');
  lines.push('```json');
  lines.push('{');
  lines.push(`  "mcpServers": {`);
  lines.push(`    "${toSlug(summary.info.title)}": {`);
  lines.push(`      "command": "npx",`);
  lines.push(`      "args": ["tsx", "./mcp-server.ts"],`);
  lines.push(`      "env": { "${auth.envVar}": "..." }`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push('}');
  lines.push('```');
  lines.push('');
  if (auth.type !== 'none') {
    lines.push(generateAuthDocs(auth));
    lines.push('');
  }
  lines.push('## Regenerate');
  lines.push('');
  lines.push('```bash');
  lines.push('npx apix generate       # regenerate everything');
  lines.push('npx apix generate client');
  lines.push('npx apix generate mcp');
  lines.push('npx apix generate python');
  lines.push('```');
  lines.push('');
  return lines.join('\n');
}
